language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

addons:
  mariadb: '10.1'

env:
  - DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'
  - DB=sqlite DB_DSN='sqlite:///:memory:'
  - DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'
    
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

  exclude:
    - php: hhvm
      env: DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'

before_install:
  - cd ../../
  - travis_retry composer create-project --dev --no-interaction cakephp/app test
  - cd test && cd vendor && mkdir multidimensional && cd multidimensional
  - mkdir cakephpify && cd ../../../
  - mv multidimension-al/cakephpify test/vendor/multidimensional/cakephpify
  - cd test && bin/cake
  - travis_retry composer require --dev phpunit/phpunit
  - travis_retry composer require --dev cakephp/cakephp-codesniffer
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --require-dev --no-interaction

script:
  - ./vendor/bin/phpcs --standard=CakePHP ./vendor/multidimensional/cakephpify/
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
