language: php
php:
  - 5.5
  - 5.6
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"

script:
  - sh -c "#"  

notifications:
  email: false