language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - DEFAULT=1
  matrix:  
    - DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test' CAKE_VERSION='3.3.*'
    - DB=sqlite DB_DSN='sqlite:///:memory:' CAKE_VERSION='3.3.*'
    #- DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test' CAKE_VERSION='3.4.*'
    #- DB=sqlite DB_DSN='sqlite:///:memory:' CAKE_VERSION='3.4.*'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 5.6
      env: CAKE_VERSION='3.4.*'
    - php: 7.0
      env: CAKE_VERSION='3.4.*'
    - php: 7.1
      env: CAKE_VERSION='3.4.*'

  include:
    - php: 5.5
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.3.*'
      addons:
        mariadb: '10.1'
    - php: 5.6
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.3.*'
      addons:
        mariadb: '10.1'
    - php: 7.0
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.3.*'
      addons:
        mariadb: '10.1'
    - php: 7.1
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.3.*'
      addons:
        mariadb: '10.1'
    - php: hhvm
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.3.*'
      addons:
        mariadb: '10.1'
    #- php: 5.6
    #  env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.4.*'
    #  addons:
    #    mariadb: '10.1'
    #- php: 7.0
    #  env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.4.*'
    #  addons:
    #    mariadb: '10.1'
    #- php: 7.1
    #  env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.4.*'
    #  addons:
    #    mariadb: '10.1'
    #- php: hhvm
    #  env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test' CAKE_VERSION='3.4.*'
    #  addons:
    #    mariadb: '10.1'*/
    - php: 7.0
      env: PHPCS=1 DEFAULT=0

  exclude:
    - php: hhvm
      env: DB=pgsql
    - php: 5.5
      env: CAKE_VERSION='3.4.*'
    - php: 5.6
      env: CAKE_VERSION='3.4.*'
    - php: 7.0
      env: CAKE_VERSION='3.4.*'
    - php: 7.1
      env: CAKE_VERSION='3.4.*'
    - php: hhvm
      env: CAKE_VERSION='3.4.*'

before_install:
  - printenv || true
  - cd ../../
  - travis_retry composer create-project cakephp/app=$CAKE_VERSION test --no-interaction -s dev
  - cd test && cd vendor && mkdir multidimensional && cd multidimensional
  - mkdir cakephpify && cd ../../../
  - mv multidimension-al/cakephpify test/vendor/multidimensional
  - cd test && bin/cake || true
  - travis_retry composer require "multidimensional/cakephpify:dev-$TRAVIS_BRANCH#$TRAVIS_COMMIT" --no-interaction
  - if [[ $DEFAULT = 1 ]] ; then travis_retry composer require "cakephp/migrations:>=1.2.0-stable" --no-interaction --prefer-stable ; fi
  - if [[ $DEFAULT = 1 ]] ; then travis_retry composer require phpunit/phpunit --no-interaction --prefer-stable ; fi
  - if [[ $PHPCS = 1 ]] ; then travis_retry composer require "cakephp/cakephp-codesniffer=2.*" --no-interaction --prefer-stable ; fi
  - if [[ $PHPCS = 1 ]] ; then ./vendor/bin/phpcs --config-set installed_paths /home/travis/build/test/vendor/cakephp/cakephp-codesniffer ; fi
  - mv -f ./vendor/multidimensional/cakephpify/tests/phpunit.xml.dist ./
  - if [[ $DB = 'mysql' ]] ; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]] ; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

before_script:
  - travis_retry composer dump-autoload --no-interaction
  - travis_retry composer update --no-interaction

script:
  - if [[ $PHPCS = 1 ]] ; then ./vendor/bin/phpcs --standard=CakePHP ./vendor/multidimensional/cakephpify/ ; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then ./vendor/bin/phpunit --coverage-text --coverage-clover=vendor/multidimensional/cakephpify/coverage.clover ; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 5.5 && $TRAVIS_PHP_VERSION != 5.6 ]] ; then ./vendor/bin/phpunit ; fi

after_script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then cd vendor/multidimensional/cakephpify/ ; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi

notifications:
  email: false
