language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  global:
    - DEFAULT=1
  matrix:  
    - DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite DB_DSN='sqlite:///:memory:'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 5.5
      env: PHPCS=1 DEFAULT=0
    
  include:
    - php: 5.5
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'  
      addons:
        mariadb: '10.1'
        
    - php: 5.6
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'  
      addons:
        mariadb: '10.1'
        
    - php: 7.0
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'  
      addons:
        mariadb: '10.1'
        
    - php: 7.1
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'  
      addons:
        mariadb: '10.1'
        
    - php: hhvm
      env: DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'  
      addons:
        mariadb: '10.1'
        
    - php: 5.5
      env: PHPCS=1 DEFAULT=0
        
  exclude:
    - php: hhvm
      env: DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'

before_install:
  - cd ../../
  - travis_retry composer create-project --no-interaction cakephp/app test
  - cd test && cd vendor && mkdir multidimensional && cd multidimensional
  - mkdir cakephpify && cd ../../../
  - mv multidimension-al/cakephpify test/vendor/multidimensional/cakephpify
  - cd test && bin/cake || true
  - travis_retry composer require phpunit/phpunit
  - travis_retry composer require "cakephp/cakephp-codesniffer=2.*"
  - ./vendor/bin/phpcs --config-set installed_paths /home/travis/build/test/vendor/cakephp/cakephp-codesniffer
  - rm -f phpunit.xml.dist
  - mv vendor/multidimensional/cakephpify/tests/phpunit.xml.dist .
  - if [[ $DB = 'mysql' ]] ; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]] ; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - if [[ $PHPCS = 1 ]] ; then ./vendor/bin/phpcs --standard=CakePHP ./vendor/multidimensional/cakephpify/; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then ./vendor/bin/phpunit --coverage-text --coverage-clover=vendor/multidimensional/cakephpify/coverage.clover vendor/multidimensional/cakephpify/; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 5.5 && $TRAVIS_PHP_VERSION != 5.6 ]] ; then ./vendor/bin/phpunit vendor/multidimensional/cakephpify/; fi

after_script:
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then cd vendor/multidimensional/cakephpify/; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.0 && $TRAVIS_PHP_VERSION != 7.1 && $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
