language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
addons:
  mariadb: '10.1'
  
env:
  matrix: 
    - DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'
    - DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite DB_DSN='sqlite:///:memory:'
    
matrix:
  allow_failures:
    - php: hhvm

  fast_finish: true

  include:
    - php: hhvm
      env: HHVM=1 DB=sqlite DB_DSN='sqlite:///:memory:'

    - php: hhvm
      env: HHVM=1 DB=mysql DB_DSN='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

before_install:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql --version; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql --version; fi"

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
