<?php
/*/
 *  DEFAULT 'shopify.php' config file.
 *
 *  This file is normally generated by running the following command in shell:
 *  bin/cake ShopifyInstall
 *
 *  If you don't have this file, copy it to your main CakePHP config folder.
/*/

return array (
  'Shopify' => 
  array (
    'api_key' => '',
    'shared_secret' => '',
    'scope' => '',
    'is_private_app' => '',
	'private_app_password' => ''
  ),
);